### ISSUE TITLE
New additional interface options for port_template type

### ISSUE THREAD

**Issue by vidarstokke** [Uninett/cnaas-nms#2]
**Is your feature request related to a problem? Please describe.**
We can't use port_template ifclass for uplinks to Uninett without these extra options. Then we need to use custom ifclass, which is not very optimal. 

**Describe the solution you'd like**
I want the following options to be optional for port_template type.

- ipv4_address: TYPE IPv4-interface with prefixlength (ie. 10.20.30.2/31)
- ipv6_address: TYPE IPv6-interface with prefixlength (ie 2001:dead:beef::1/127)
- mtu: TYPE string or integer (ie. 9192)
- acl_ipv4_in: TYPE string (ie. edge-in-v4)
- acl_ipv4_out: TYPE string (ie. edge-out-v4)
- acl_ipv6_in: TYPE string (ie. edge-in-v6)
- acl_ipv6_out: TYPE string (ie. edge-out-v6)

**Describe alternatives you've considered**
Alcohol. Also using ifclass "custom" which will be suboptimal.

**Additional context**
See https://cnaas-nms.readthedocs.io/en/latest/reporef/index.html?highlight=port_template#settings to see what is available options today.

**Comment by lunkwill42** [comment]
Additions/changes to the default configuration schemas are maintained in our internal deployment repo in Gitlab. Changes have been made there and deployed to our lab installation for you testing pleasure, @vidarstokke

**Comment by vidarstokke** [comment]
Works like a charm.
